Fixed run-tests.

diff --git a/gecode/string/tests/run-tests b/gecode/string/tests/run-tests
--- a/gecode/string/tests/run-tests
+++ b/gecode/string/tests/run-tests
@@ -53,6 +53,13 @@ then
       fi
     done
   fi
+  ret=$?
+  if 
+    [[ $ret -ne 0 ]]
+  then
+    echo "Error $ret"
+    exit $ret
+  fi
   declare -a TESTS=( \
       'str_test1.cpp' 'str_test2.cpp' 'str_ex1.cpp' 'str_ex2.cpp' 'str_ex3.cpp'\
       'str_ex4.cpp' 'str_ex5.cpp' 'str_ex6.cpp' 'str_ex7.cpp' 'str_ex8.cpp'\
