Improved blockmin_llll strategy and sweep algorithm.

diff --git a/gecode/string/tests/run-tests b/gecode/string/tests/run-tests
--- a/gecode/string/tests/run-tests
+++ b/gecode/string/tests/run-tests
@@ -142,6 +142,40 @@ do
     exit 1
   fi
 done &&
+#for m in `ls $TEST_DIR/stranger/*.mzn | sort`
+#do
+#  timeout 10 mzn-gstrings $m 2>/dev/null > $X
+#  if
+#    [[ `grep "\----------" $X` ]]
+#  then
+#    m=`basename $m`
+##    res=`grep $m $TEST_DIR/stranger/stranger_check.txt | awk '{print $2}'`
+##    if
+##      [[ $res == "sat" ]]
+##    then
+##      echo "Solved $m!"
+##    else
+##      echo "Error! $m not sound."
+##      exit 1
+##    fi
+#  elif 
+#    [[ `grep "=====UNSATISFIABLE=====" $X` ]]
+#  then
+#    m=`basename $m`
+##    res=`grep $m $TEST_DIR/stranger/stranger_check.txt | awk '{print $2}'`
+##    if
+##      [[ $res == "uns" ]]
+##    then
+##      echo "Solved $m!"
+##    else
+##      echo "Error! $m not sound."
+##      exit 1
+##    fi
+#  else
+#    echo "Error! $m not sound."
+##    exit 1
+#  fi
+#done &&
 for m in `ls $TEST_DIR/norn/*/*.mzn | sort`
 do
   echo "Solving $m..."
