Setting 2026 benchmark.

diff --git a/gecode/string/tests/match-experiments/journal/baseline_2026/dna_match/run_gstrings b/gecode/string/tests/match-experiments/journal/baseline_2026/dna_match/run_gstrings
--- a/gecode/string/tests/match-experiments/journal/baseline_2026/dna_match/run_gstrings
+++ b/gecode/string/tests/match-experiments/journal/baseline_2026/dna_match/run_gstrings
@@ -1,103 +1,90 @@
-#! /bin/bash
+#!/usr/bin/env bash
 
-EXP_PATH=$HOME/G-Strings/gecode/gecode/string/tests/match-experiments/journal/dna_match
+set -o pipefail
 
-# Time-out in seconds for constraint solving.
-TIMEOUT=300
+EXP_PATH=$(cd "$(dirname "$0")" && pwd)
+TIMEOUT=${TIMEOUT:-300}
+MAX_INSTANCES=${MAX_INSTANCES:-0}
+SOLVERS=${SOLVERS:-"G-Strings_ori G-Strings_new G-Strings_dec"}
 
-# Errors log file.
-ERRORS=$EXP_PATH'/errors_gstrings_dna.log'
+ERRORS="$EXP_PATH/errors_gstrings_dna.log"
+OUTPUT="$EXP_PATH/output_gstrings_dna.log"
+RESULTS="$EXP_PATH/results_gstrings_dna.log"
 
-# Output log file.
-OUTPUT=$EXP_PATH'/output_gstrings_dna.log'
+WORK=$(mktemp -d)
+trap 'rm -rf "$WORK"' EXIT
+ERR="$WORK/tmp.err"
+OUT="$WORK/tmp.out"
+TIMING="$WORK/tmp.time"
+VALUES="$WORK/tmp.values"
+FZN="$WORK/tmp.fzn"
 
-# Output log file.
-RESULTS=$EXP_PATH'/results_gstrings_dna.log'
+: > "$ERRORS"
+: > "$OUTPUT"
+: > "$RESULTS"
 
-# Auxiliary files
-ERR=$EXP_PATH'/tmp.err'
-OUT=$EXP_PATH'/tmp.out'
-TMP=$EXP_PATH'/tmp.tmp'
-FZN=$EXP_PATH'/tmp.fzn'
-echo '' > $ERR
-echo '' > $OUT
-echo '' > $TMP
-echo '' > $FZN
+mapfile -t instances < <(find "$EXP_PATH/dzn" -maxdepth 1 -type f -name '*.dzn' | sort -V)
+if [ "$MAX_INSTANCES" -gt 0 ]; then
+  instances=("${instances[@]:0:$MAX_INSTANCES}")
+fi
 
-for solver in 'G-Strings_new' 'G-Strings_ori'
+for solver in $SOLVERS
 do
-  mzn=$EXP_PATH/dna.mzn
-  for dzn in `ls $EXP_PATH/dzn/*.dzn | sort -n`
+  case "$solver" in
+    G-Strings_ori) mzn="$EXP_PATH/dna.mzn"; define='newM=false' ;;
+    G-Strings_new) mzn="$EXP_PATH/dna.mzn"; define='newM=true' ;;
+    G-Strings_dec) mzn="$EXP_PATH/dna_dec.mzn"; define='newM=false' ;;
+    *) echo "Unknown solver variant: $solver" >&2; exit 1 ;;
+  esac
+
+  for dzn in "${instances[@]}"
   do
     header="$solver|$dzn"
-    echo $header >> $ERRORS
-    echo $header >> $OUTPUT
-#    if
-#      [[ "$solver" == 'G-Strings_dec' ]]
-#    then
-#      mzn=$EXP_PATH'/shortest_match_dec.mzn'
-    if
-      [[ "$solver" == 'G-Strings_new' ]]
-    then  
-      D=true
-    else
-      D=false
-    fi
+    echo "$header" | tee -a "$ERRORS" "$OUTPUT"
+
     echo "Converting MiniZinc model to FlatZinc..."
-    echo "mzn2fzn-gstrings -D"newM=$D" $mzn $dzn -o $FZN"
-    mzn2fzn-gstrings -D"newM=$D" $mzn $dzn -o $FZN
+    echo "mzn2fzn-gstrings -D\"$define\" $mzn $dzn -o $FZN"
+    if ! mzn2fzn-gstrings -D"$define" "$mzn" "$dzn" -o "$FZN" 2>"$ERR"; then
+      cat "$ERR" | tee -a "$ERRORS" >&2
+      echo "$header|err|nan|{}|0" >> "$RESULTS"
+      continue
+    fi
+
     echo "Solving FlatZinc instance..."
-    
-    start=`awk 'BEGIN {print systime()}'`
-    time -p (unbuffer timeout $TIMEOUT fzn-gstrings -decomp-regex 0 -a $FZN 2>$ERR | gawk -v s=$start \
-    '{print $0, (systime() - s)}' 1>$OUT) 2>$TMP
+    start=$(awk 'BEGIN {print systime()}')
+    { time -p unbuffer timeout "$TIMEOUT" fzn-gstrings -decomp-regex 0 -a "$FZN" 2>"$ERR" |
+        gawk -v s="$start" '{print $0, (systime() - s)}' >"$OUT"; } 2>"$TIMING"
     ret=$?
-    ini_time=0 # Here one can put fzn time...
-    tot_time=`cat $TMP | awk -v it=$ini_time 'NR == 1 {print $2 - it}'`
-    cat $OUT | grep 'obj = ' | awk '{print $3, $4}' | sed 's/;//g' | sed 's/ /_,_/g' > $TMP
+    tot_time=$(awk '/^real / {print $2; exit}' "$TIMING")
+    tot_time=${tot_time:-0}
+
+    grep 'obj = ' "$OUT" | awk '{print $3, $4}' | sed 's/;//g' | sed 's/ /_,_/g' > "$VALUES"
     vals='{'
-    for i in `cat $TMP`
+    key=''
+    while read -r item
     do
-      key=`echo $i | awk -F"_,_" '{print $1}'`
-      value=`echo $i | awk -v it=$ini_time -F"_,_" '{print $2 - it}'`
-      vals=$vals''$key': '$value', '
-    done
-    if 
-      [ "$vals" == '{' ]
-    then
-      val='nan'
+      [ -z "$item" ] && continue
+      key=$(echo "$item" | awk -F'_,_' '{print $1}')
+      value=$(echo "$item" | awk -F'_,_' '{print $2}')
+      vals="$vals$key: $value, "
+    done < "$VALUES"
+    if [ -z "$key" ]; then val=nan; else val=$key; fi
+    vals="$vals}"
+
+    if grep -q '=====UNKNOWN=====' "$OUT"; then
+      status=unk
+    elif grep -q -- '----------' "$OUT"; then
+      if grep -q '==========' "$OUT"; then status=opt; else status=sat; fi
+    elif grep -q '=====UNSATISFIABLE=====' "$OUT"; then
+      status=uns
+    elif [ "$ret" -eq 124 ]; then
+      status=unk
     else
-      val=$key
+      status=err
     fi
-    vals=$vals'}'
-    
-    if
-      [[ -n "`grep =====UNKNOWN===== $OUT`" ]]
-    then
-      s='unk'
-    elif
-      [[ -n "`grep "\----------" $OUT`" ]]
-    then
-      if
-        [[ -n "`grep ========== $OUT`"  ]]
-      then
-        s='opt'
-      else
-        s='sat'
-      fi
-    elif
-      [[ -n "`grep =====UNSATISFIABLE===== $OUT`" ]]
-    then
-      s='uns'
-    else
-      s='unk'
-    fi
-    
-    cat $ERR >> $ERRORS
-    cat $OUT >> $OUTPUT
-    echo $header'|'$s'|'$val'|'$vals'|'$tot_time >> $RESULTS
-    cp $RESULTS ~/Dropbox
+
+    cat "$ERR" >> "$ERRORS"
+    cat "$OUT" >> "$OUTPUT"
+    echo "$header|$status|$val|$vals|$tot_time" | tee -a "$RESULTS"
   done
 done
-
-rm $OUT $ERR $TMP $FZN
diff --git a/gecode/string/tests/match-experiments/journal/baseline_2026/latin_square/run_gstrings b/gecode/string/tests/match-experiments/journal/baseline_2026/latin_square/run_gstrings
--- a/gecode/string/tests/match-experiments/journal/baseline_2026/latin_square/run_gstrings
+++ b/gecode/string/tests/match-experiments/journal/baseline_2026/latin_square/run_gstrings
@@ -1,74 +1,68 @@
-#! /bin/bash
+#!/usr/bin/env bash
 
-EXP_PATH=$HOME/G-Strings/gecode/gecode/string/tests/match-experiments/journal/latin_square
+set -o pipefail
 
-# Time-out in seconds for constraint solving.
-TIMEOUT=300
+EXP_PATH=$(cd "$(dirname "$0")" && pwd)
+TIMEOUT=${TIMEOUT:-300}
+N_MIN=${N_MIN:-2}
+N_MAX=${N_MAX:-26}
+SOLVERS=${SOLVERS:-"G-Strings_ori G-Strings_new G-Strings_dec"}
 
-# Errors log file.
-ERRORS=$EXP_PATH'/errors_gstrings_ls.log'
+ERRORS="$EXP_PATH/errors_gstrings_ls.log"
+OUTPUT="$EXP_PATH/output_gstrings_ls.log"
+RESULTS="$EXP_PATH/results_gstrings_ls.log"
 
-# Output log file.
-OUTPUT=$EXP_PATH'/output_gstrings_ls.log'
+WORK=$(mktemp -d)
+trap 'rm -rf "$WORK"' EXIT
+ERR="$WORK/tmp.err"
+OUT="$WORK/tmp.out"
+TIMING="$WORK/tmp.time"
+FZN="$WORK/tmp.fzn"
 
-# Output log file.
-RESULTS=$EXP_PATH'/results_gstrings_ls.log'
+: > "$ERRORS"
+: > "$OUTPUT"
+: > "$RESULTS"
 
-# Auxiliary files
-ERR=$EXP_PATH'/tmp.err'
-OUT=$EXP_PATH'/tmp.out'
-TMP=$EXP_PATH'/tmp.tmp'
-FZN=$EXP_PATH'/tmp.fzn'
-echo '' > $ERR
-echo '' > $OUT
-echo '' > $TMP
-echo '' > $FZN
-echo '' > $RESULTS
-
-for solver in 'G-Strings_new' 'G-Strings_ori'
+for solver in $SOLVERS
 do
-  for i in {2..40}
+  case "$solver" in
+    G-Strings_ori) mzn="$EXP_PATH/latin_square.mzn" ;;
+    G-Strings_new) mzn="$EXP_PATH/latin_square_new.mzn" ;;
+    G-Strings_dec) mzn="$EXP_PATH/latin_square_dec.mzn" ;;
+    *) echo "Unknown solver variant: $solver" >&2; exit 1 ;;
+  esac
+
+  for ((i=N_MIN; i<=N_MAX; i++))
   do
-    dzn="-D\"N=$i\""
     header="$solver|$i"
-    echo $header >> $ERRORS
-    echo $header >> $OUTPUT
-    if
-      [[ "$solver" == 'G-Strings_dec' ]]
-    then
-      mzn=$EXP_PATH'/latin_square_dec.mzn'
-    elif
-      [[ "$solver" == 'G-Strings_new' ]]
-    then
-      mzn=$EXP_PATH'/latin_square_new.mzn'
-    else
-      mzn=$EXP_PATH'/latin_square.mzn'
-    fi
+    echo "$header" | tee -a "$ERRORS" "$OUTPUT"
+
     echo "Converting MiniZinc model to FlatZinc..."
     echo "mzn2fzn-gstrings -D\"N=$i\" $mzn -o $FZN"
-    mzn2fzn-gstrings -D"N=$i" $mzn -o $FZN
-    echo "Solving FlatZinc instance..."
-    
-    start=`awk 'BEGIN {print systime()}'`
-    time -p (timeout $TIMEOUT fzn-gstrings -s $FZN 2>$ERR | gawk -v s=$start \
-    '{print $0, (systime() - s)}') 1>$OUT 2>$TMP
-    ret=$?
-    ini_time=0 # Here one can put fzn time...
-    tot_time=`cat $TMP | awk -v it=$ini_time 'NR == 1 {print $2 - it}'`
-    
-    if
-      [[ -n "`grep "\----------" $OUT`" ]]
-    then
-      s='sat'
-    else
-      s='unk'
+    if ! mzn2fzn-gstrings -D"N=$i" "$mzn" -o "$FZN" 2>"$ERR"; then
+      cat "$ERR" | tee -a "$ERRORS" >&2
+      echo "$header|err|0" >> "$RESULTS"
+      continue
     fi
-    
-    cat $ERR >> $ERRORS
-    cat $OUT >> $OUTPUT
-    echo $header'|'$s'|'$tot_time >> $RESULTS
-    cp $RESULTS ~/Dropbox
+
+    echo "Solving FlatZinc instance..."
+    start=$(awk 'BEGIN {print systime()}')
+    { time -p timeout "$TIMEOUT" fzn-gstrings -s "$FZN" 2>"$ERR" |
+        gawk -v s="$start" '{print $0, (systime() - s)}' >"$OUT"; } 2>"$TIMING"
+    ret=$?
+    tot_time=$(awk '/^real / {print $2; exit}' "$TIMING")
+    tot_time=${tot_time:-0}
+
+    if grep -q -- '----------' "$OUT"; then
+      status=sat
+    elif [ "$ret" -eq 124 ]; then
+      status=unk
+    else
+      status=unk
+    fi
+
+    cat "$ERR" >> "$ERRORS"
+    cat "$OUT" >> "$OUTPUT"
+    echo "$header|$status|$tot_time" | tee -a "$RESULTS"
   done
 done
-
-rm $OUT $ERR $TMP $FZN
diff --git a/gecode/string/tests/match-experiments/journal/baseline_2026/latin_square/run_smt b/gecode/string/tests/match-experiments/journal/baseline_2026/latin_square/run_smt
--- a/gecode/string/tests/match-experiments/journal/baseline_2026/latin_square/run_smt
+++ b/gecode/string/tests/match-experiments/journal/baseline_2026/latin_square/run_smt
@@ -1,79 +1,64 @@
-#! /bin/bash
+#!/usr/bin/env bash
 
-EXP_PATH=$HOME'/G-Strings/gecode/gecode/string/tests/match-experiments/journal/latin_square'
+set -o pipefail
 
-# Time-out in seconds for constraint solving.
-TIMEOUT=300
+EXP_PATH=$(cd "$(dirname "$0")" && pwd)
+TIMEOUT=${TIMEOUT:-300}
+MAX_INSTANCES=${MAX_INSTANCES:-0}
+SOLVERS=${SOLVERS:-"cvc5 z3seq"}
 
-# Errors log file.
-ERRORS=$EXP_PATH'/errors_smt_ls.log'
+ERRORS="$EXP_PATH/errors_smt_ls.log"
+OUTPUT="$EXP_PATH/output_smt_ls.log"
+RESULTS="$EXP_PATH/results_smt_ls.log"
 
-# Output log file.
-OUTPUT=$EXP_PATH'/output_smt_ls.log'
+WORK=$(mktemp -d)
+trap 'rm -rf "$WORK"' EXIT
+ERR="$WORK/tmp.err"
+OUT="$WORK/tmp.out"
+TIMING="$WORK/tmp.time"
 
-# Output log file.
-RESULTS=$EXP_PATH'/results_smt_ls.log'
+: > "$ERRORS"
+: > "$OUTPUT"
+: > "$RESULTS"
 
-# Auxiliary files
-ERR=$EXP_PATH'/tmp.err'
-OUT=$EXP_PATH'/tmp.out'
-TMP=$EXP_PATH'/tmp.tmp'
-SMT=$EXP_PATH'/tmp.smt2'
-echo '' > $ERR
-echo '' > $OUT
-echo '' > $TMP
-echo '' > $SMT
+mapfile -t instances < <(find "$EXP_PATH/smt" -maxdepth 1 -type f -name 'ls_*.smt2' | sort -V)
+if [ "$MAX_INSTANCES" -gt 0 ]; then
+  instances=("${instances[@]:0:$MAX_INSTANCES}")
+fi
 
-for solver in z3str #cvc5 #z3seq
+for solver in $SOLVERS
 do
-  for smt in `ls $EXP_PATH/smt/*.smt2 | sort -n | grep ls_[3-5].smt2` #FIXME
+  case "$solver" in
+    z3seq) cmd=(z3 -smt2 smt.string_solver=seq) ;;
+    cvc5) cmd=(cvc5 --lang=smt2) ;;
+    *) echo "Unknown SMT solver: $solver" >&2; exit 1 ;;
+  esac
+
+  for smt in "${instances[@]}"
   do
     header="$solver|$smt"
-    echo $header >> $ERRORS
-    echo $header >> $OUTPUT
-
-    if
-      [ "$solver" == "z3str" ]
-    then
-      CMD="z3 -smt2 smt.string_solver=z3str3 "
-    elif
-      [ "$solver" == "z3seq"  ]
-    then
-      CMD="z3 -smt2 smt.string_solver=seq"
-    elif 
-      [ "$solver" == "cvc5" ]
-    then
-      CMD="cvc5 --lang smt --strings-exp "
-    else
-      exit 1
-    fi
-    
+    echo "$header" | tee -a "$ERRORS" "$OUTPUT"
     echo "Solving $smt with $solver..."
-    start=`awk 'BEGIN {print systime()}'`
-    time -p (timeout $TIMEOUT $CMD $smt 2>$ERR | \
-      gawk -v s=$start '{print $0, (systime() - s)}' 1>$OUT) 2>$TMP
+
+    start=$(awk 'BEGIN {print systime()}')
+    { time -p timeout "$TIMEOUT" "${cmd[@]}" "$smt" 2>"$ERR" |
+        gawk -v s="$start" '{print $0, (systime() - s)}' >"$OUT"; } 2>"$TIMING"
     ret=$?
+    tot_time=$(awk '/^real / {print $2; exit}' "$TIMING")
+    tot_time=${tot_time:-0}
 
-    ini_time=0
-    tot_time=`cat $TMP | awk -v it=$ini_time 'NR == 1 {print $2 - it}'`
- 
-    if
-      [[ -n "`grep "sat" $OUT`" ]]
-    then
-      s='sat'
+    if grep -Eq '^sat([[:space:]]|$)' "$OUT"; then
+      status=sat
+    elif grep -Eq '^unsat([[:space:]]|$)' "$OUT"; then
+      status=uns
+    elif [ "$ret" -eq 124 ] || grep -Eq '^unknown([[:space:]]|$)' "$OUT"; then
+      status=unk
     else
-      s='unk'
+      status=err
     fi
-    
-    cat $ERR >> $ERRORS
-    cat $OUT >> $OUTPUT
-    echo $header'|'$s'|'$tot_time >> $RESULTS
-    cp $RESULTS ~/Dropbox
-    echo "Sleeping 3 seconds..."
-    sleep 3
-  done
-  echo "Sleeping 10 seconds..."
-  sleep 10
-done
 
-rm $OUT $ERR $TMP
+    cat "$ERR" >> "$ERRORS"
+    cat "$OUT" >> "$OUTPUT"
+    echo "$header|$status|$tot_time" | tee -a "$RESULTS"
+  done
+done
diff --git a/gecode/string/tests/match-experiments/journal/baseline_2026/shortest_match/run_smt b/gecode/string/tests/match-experiments/journal/baseline_2026/shortest_match/run_smt
--- a/gecode/string/tests/match-experiments/journal/baseline_2026/shortest_match/run_smt
+++ b/gecode/string/tests/match-experiments/journal/baseline_2026/shortest_match/run_smt
@@ -1,125 +1,103 @@
-#! /bin/bash
+#!/usr/bin/env bash
 
-EXP_PATH=$HOME'/G-Strings/gecode/gecode/string/tests/match-experiments/journal/shortest_match'
+set -o pipefail
 
-# Time-out in seconds for constraint solving.
-TIMEOUT=300
+EXP_PATH=$(cd "$(dirname "$0")" && pwd)
+TIMEOUT=${TIMEOUT:-300}
+MAX_INSTANCES=${MAX_INSTANCES:-0}
+SOLVERS=${SOLVERS:-"cvc5 z3seq"}
 
-# Errors log file.
-ERRORS=$EXP_PATH'/errors_smt_sm.log'
+ERRORS="$EXP_PATH/errors_smt_sm.log"
+OUTPUT="$EXP_PATH/output_smt_sm.log"
+RESULTS="$EXP_PATH/results_smt_sm.log"
 
-# Output log file.
-OUTPUT=$EXP_PATH'/output_smt_sm.log'
+WORK=$(mktemp -d)
+trap 'rm -rf "$WORK"' EXIT
+ERR="$WORK/tmp.err"
+OUT="$WORK/tmp.out"
+TIMING="$WORK/tmp.time"
+VALUES="$WORK/tmp.values"
+SMT="$WORK/tmp.smt2"
 
-# Output log file.
-RESULTS=$EXP_PATH'/results_smt_sm.log'
-
-# Auxiliary files
-ERR=$EXP_PATH'/tmp.err'
-OUT=$EXP_PATH'/tmp.out'
-TMP=$EXP_PATH'/tmp.tmp'
-SMT=$EXP_PATH'/tmp.smt2'
-echo '' > $ERR
-echo '' > $OUT
-echo '' > $TMP
-echo '' > $SMT
-
-Z3SEQ="z3 -smt2 smt.string_solver=seq "
-Z3STR="z3 -smt2 smt.string_solver=z3str3 "
-CVC5="cvc5 --produce-models --lang smt --strings-exp "
-CMD="$EXP_PATH/smt_min"
 OBJ=min
 OBJVAR=L
+CMD="$EXP_PATH/smt_min"
 
-for solver in z3seq cvc5 z3str
+: > "$ERRORS"
+: > "$OUTPUT"
+: > "$RESULTS"
+
+mapfile -t instances < <(find "$EXP_PATH/smt" -maxdepth 1 -type f -name 'sm_*.smt2' | sort -V)
+if [ "$MAX_INSTANCES" -gt 0 ]; then
+  instances=("${instances[@]:0:$MAX_INSTANCES}")
+fi
+
+for solver in $SOLVERS
 do
-  for smt in `ls $EXP_PATH/smt/sm* | grep "_512_\|_25.smt" | sort -n` #FIXME
+  case "$solver" in
+    z3seq) initial=(z3 -smt2 smt.string_solver=seq) ;;
+    cvc5) initial=(cvc5 --produce-models --lang=smt2 --strings-exp) ;;
+    *) echo "Unknown SMT solver: $solver" >&2; exit 1 ;;
+  esac
+
+  for smt in "${instances[@]}"
   do
     header="$solver|$smt"
-    echo $header >> $ERRORS
-    echo $header >> $OUTPUT
-   
+    echo "$header" | tee -a "$ERRORS" "$OUTPUT"
+
     echo "Extracting initial bound for $smt..."
-    cp $smt $SMT
-    echo '(get-model)' >> $SMT
-    if
-      [ "$solver" == "z3str" ]
-    then
-      v=`timeout 1 $Z3STR $SMT | tr '\n' ' ' | sed 's/define-fun/\n/g' | grep "$OBJVAR ()" | awk '{print $4}' | sed 's/)//g'`
-    elif
-      [ "$solver" == "z3seq" ]
-    then
-      v=`timeout 1 $Z3SEQ $SMT | tr '\n' ' ' | sed 's/define-fun/\n/g' | grep "$OBJVAR ()" | awk '{print $4}' | sed 's/)//g'`
-    elif 
-      [ "$solver" == "cvc5" ]
-    then
-      v=`timeout 1 $CVC5 $SMT | grep "$OBJVAR ()" | awk '{print $5}' | sed 's/)//g'`
+    cp "$smt" "$SMT"
+    echo '(get-model)' >> "$SMT"
+
+    if [ "$solver" = z3seq ]; then
+      v=$(timeout 1 "${initial[@]}" "$SMT" 2>/dev/null | tr '\n' ' ' |
+          sed 's/define-fun/\n/g' | grep "$OBJVAR ()" | awk '{print $4}' | sed 's/)//g' | head -1)
     else
-      exit 1
+      v=$(timeout 1 "${initial[@]}" "$SMT" 2>/dev/null | grep "$OBJVAR ()" |
+          awk '{print $5}' | sed 's/)//g' | head -1)
     fi
-    if
-      [ -n "$v" ]
-    then
+
+    if [ -n "$v" ]; then
       val=$v
     else
-      val=`basename $smt | awk -F"_" '{print $2}' | sed 's/.smt2//g'`
+      val=$(basename "$smt" | awk -F_ '{print $2}')
     fi
+
     echo "Initial bound = $val. Solving $smt with $solver..."
-    start=`awk 'BEGIN {print systime()}'`
-    time -p (unbuffer timeout $TIMEOUT $CMD $smt $OBJVAR $val $solver $OBJ 2>$ERR | \
-    gawk -v s=$start '{print $0, (systime() - s)}' 1>$OUT) 2>$TMP
+    start=$(awk 'BEGIN {print systime()}')
+    { time -p unbuffer timeout "$TIMEOUT" "$CMD" "$smt" "$OBJVAR" "$val" "$solver" "$OBJ" 2>"$ERR" |
+        gawk -v s="$start" '{print $0, (systime() - s)}' >"$OUT"; } 2>"$TIMING"
     ret=$?
-#    pkill sleep
+    tot_time=$(awk '/^real / {print $2; exit}' "$TIMING")
+    tot_time=${tot_time:-0}
 
-    ini_time=0
-    tot_time=`cat $TMP | awk -v it=$ini_time 'NR == 1 {print $2 - it}'`
-    cat $OUT | grep "$OBJVAR = " | awk '{print $3, $4}' | sed 's/;//g' | sed 's/ /_,_/g' > $TMP
+    grep "$OBJVAR = " "$OUT" | awk '{print $3, $4}' | sed 's/;//g' | sed 's/ /_,_/g' > "$VALUES"
     vals='{'
-    for i in `cat $TMP`
+    key=''
+    while read -r item
     do
-      key=`echo $i | awk -F"_,_" '{print $1}'`
-      value=`echo $i | awk -v it=$ini_time -F"_,_" '{print $2 - it}'`
-      vals=$vals''$key': '$value', '
-    done
-    if 
-      [ "$vals" == '{' ]
-    then
-      val='nan'
-    else
-      val=$key
-    fi
-    vals=$vals'}'
-    
-    if
-      [[ -n "`grep =====UNKNOWN===== $OUT`" ]]
-    then
-      s='unk'
-    elif
-      [[ -n "`grep "\----------" $OUT`" ]]
-    then
-      if
-        [[ -n "`grep ========== $OUT`"  ]]
-      then
-        s='opt'
-      else
-        s='sat'
-      fi
-    elif
-      [[ -n "`grep =====UNSATISFIABLE===== $OUT`" ]]
-    then
-      s='uns'
-    else
-      s='unk'
-    fi
-    cat $ERR >> $ERRORS
-    cat $OUT >> $OUTPUT
-    echo $header'|'$s'|'$val'|'$vals'|'$tot_time >> $RESULTS
-    cp $RESULTS ~/Dropbox
-    echo "Sleeping 3 seconds..."
-    sleep 3
-  done
-  echo "Sleeping 10 seconds..."
-  sleep 10
-done
+      [ -z "$item" ] && continue
+      key=$(echo "$item" | awk -F'_,_' '{print $1}')
+      value=$(echo "$item" | awk -F'_,_' '{print $2}')
+      vals="$vals$key: $value, "
+    done < "$VALUES"
+    if [ -z "$key" ]; then val=nan; else val=$key; fi
+    vals="$vals}"
 
-rm $OUT $ERR $TMP
+    if grep -q '=====UNKNOWN=====' "$OUT"; then
+      status=unk
+    elif grep -q -- '----------' "$OUT"; then
+      if grep -q '==========' "$OUT"; then status=opt; else status=sat; fi
+    elif grep -q '=====UNSATISFIABLE=====' "$OUT"; then
+      status=uns
+    elif [ "$ret" -eq 124 ]; then
+      status=unk
+    else
+      status=err
+    fi
+
+    cat "$ERR" >> "$ERRORS"
+    cat "$OUT" >> "$OUTPUT"
+    echo "$header|$status|$val|$vals|$tot_time" | tee -a "$RESULTS"
+  done
+done
