Added PISA benchmarks.

diff --git a/gecode/string/sandbox/run-tests b/gecode/string/sandbox/run-tests
--- a/gecode/string/sandbox/run-tests
+++ b/gecode/string/sandbox/run-tests
@@ -64,6 +64,50 @@ else
 fi &&
 # FIXME: Timeout depends on the target machine.
 TOUT=2
+for m in `ls $TEST_DIR/pisa/*.mzn | sort -n`
+do
+  timeout $TOUT mzn-dashed $m > $X
+  ret=$?
+  m=`basename $m`
+  if
+    [[ `grep "\----------" $X` ]]
+  then
+#    cat $X | grep -v "\----------" > $Y.dzn
+    res=`grep $m $TEST_DIR/pisa/pisa_check.txt | awk '{print $2}'`
+    if
+      [[ $res == "SAT" ]]
+    then
+      echo "$m sat"
+    else
+      echo "Error! $m incorrect."
+      rm $X
+      exit 1
+    fi
+  elif 
+    [[ `grep "=====UNSATISFIABLE=====" $X` ]]
+  then
+    res=`grep $m $TEST_DIR/pisa/pisa_check.txt | awk '{print $2}'`
+    if
+      [[ $res == "UNSAT" ]]
+    then
+      echo "$m unsat"
+    else
+      echo "Error! $m incorrect."
+      rm $X
+      exit 1
+    fi
+  else
+    if
+      [[ $ret -eq 124 ]]
+    then
+      echo "$m timeout"
+    else
+      echo "$m unknown"
+      rm $X
+      exit 1
+    fi
+  fi
+done &&
 for m in `ls $TEST_DIR/woorpje/*.mzn | sort -n`
 do
   timeout $TOUT mzn-dashed $m > $X
