Starting the debug on woorpje benchmarks.

diff --git a/gecode/string/sandbox/run-tests b/gecode/string/sandbox/run-tests
--- a/gecode/string/sandbox/run-tests
+++ b/gecode/string/sandbox/run-tests
@@ -51,16 +51,64 @@ then
       done
 fi &&
 mzn-dashed $TEST_DIR/test.mzn > $X
-Y=$TEST_DIR/output_mzn;
-diff $X $Y > $Z
+diff $X $TEST_DIR/output_mzn > $Y
 if
-  [ -s $Z ]
+  [ -s $Y ]
 then
-  echo "Error! MZN output not expected!"
-  cat $Z
+  echo "Error! MZN output not expected. See $X and $Y logs."
+  cat $Y
   exit 1
 else
   cat $X
-  rm $X $Z
+  rm $Y
 fi &&
+# FIXME: Timeout depends on the target machine.
+TOUT=2
+for m in `ls $TEST_DIR/woorpje/01_track_*.mzn | sort`
+do
+  timeout $TOUT mzn-dashed $m > $X
+  ret=$?
+  if
+    [[ `grep "\----------" $X` ]]
+  then
+    echo "$m sat"
+#    m=`basename $m`
+#    res=`grep $m $TEST_DIR/pisa/pisa_check.txt | awk '{print $2}'`
+#    if
+#      [[ $res == "sat" ]]
+#    then
+#      echo "Solved $m!"
+#    else
+#      echo "Error! $m not sound."
+#      rm $X
+#      exit 1
+#    fi
+  elif 
+    [[ `grep "=====UNSATISFIABLE=====" $X` ]]
+  then
+    echo "$m unsat"
+#    m=`basename $m`
+#    res=`grep $m $TEST_DIR/pisa/pisa_check.txt | awk '{print $2}'`
+#    if
+#      [[ $res == "uns" ]]
+#    then
+#      echo "Solved $m!"
+#    else
+#      echo "Error! $m not sound."
+#      rm $X
+#      exit 1
+#    fi
+  else
+    if
+      [[ $ret -eq 124 ]]
+    then
+      echo "$m timeout"
+    else
+      echo "$m not sound"
+#    rm $X
+#    exit 1
+    fi
+  fi
+done &&
 echo "===== All tests pass! ====="
+rm $X
